name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Grant necessary permissions for the GITHUB_TOKEN
permissions:
  contents: write # Allows pushing to gh-pages branch
  pages: write # Allows managing GitHub Pages deployments
  id-token: write # Required for OIDC, often used with Pages

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    # if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git-based MkDocs features

      - name: Set up Python
        uses: actions/setup-python@v5 # Changed to v5 for latest features/bug fixes
        with:
          python-version: 3.x
          cache: "pip" # Cache pip dependencies

      - name: Cache MkDocs build artifacts
        id: cache-mkdocs-material
        uses: actions/cache@v4 # Changed to v4
        with:
          key: mkdocs-material-${{ hashFiles('requirements.txt') }} # Key based on requirements.txt hash
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install all dependencies from requirements.txt
          pip install -r requirements.txt
          pip install -e .

      - name: Build and deploy MkDocs
        run: mkdocs gh-deploy --force --clean
